AspNet2/ViewModels/TFAViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AspNet2.ViewModels
{
    public class TFAViewModel
    {
        public ClaimsIdentity User { get; set; }

        public String UserId 
        { 
            get { return User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).FirstOrDefault()?.Value ?? throw new ArgumentException(nameof(ClaimTypes.NameIdentifier)); } 
        }

        public String UserName 
        { 
            get { return User.Claims.Where(c => c.Type == ClaimTypes.Name).FirstOrDefault()?.Value ?? throw new ArgumentException(nameof(ClaimTypes.Name)); } 
        }

        public String RandomKey { get; set; }
        
        public String RandomKeyFormatted { get; set; }
        
        public String QRCodeData { get; set; }
    }
}

AspNet2/Controllers/TFAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using AspNet2.AppLib.Tools;
using AspNet2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OtpNet;

namespace AspNet2.Controllers
{
    public class TFAManager
    {
        public const string AppUriFormat = "otpauth://totp/{0}:{1}?secret={2}&issuer={0}&digits=6";

        /// <summary>
        /// Generates a random 160-bit Base32-Encoded security key 
        /// </summary>
        /// <returns></returns>
        public static string GetAuthenticatorKey()
        {
            using (RandomNumberGenerator generator = RandomNumberGenerator.Create())
            {
                byte[] bytes = new byte[20];  // size of SHA1 hash          
                generator.GetBytes(bytes);
                return Base32.ToBase32(bytes);
            }
        }

        public static string FormatKey(string unformattedKey)
        {
            int currentPosition = 0;
            
            StringBuilder result = new StringBuilder();
            
            while (currentPosition + 4 < unformattedKey.Length)
            {
                result.Append(unformattedKey.Substring(currentPosition, 4)).Append(" ");
                currentPosition += 4;
            }

            if (currentPosition < unformattedKey.Length) result.Append(unformattedKey.Substring(currentPosition));

            return result.ToString().ToLowerInvariant();
        }

        public static string QrCodeUri(string caption, string name, string unformattedKey)
        {
            return string.Format(AppUriFormat, System.Web.HttpUtility.UrlEncode(caption), System.Web.HttpUtility.UrlEncode(name), unformattedKey);
        }

        public static int GetAuthenticatorCode(string unformattedKey)
        {
            long unixTimestamp = (DateTime.UtcNow.Ticks - 621355968000000000L) / 10000000L;

            long window = unixTimestamp / (long)30;

            byte[] keyBytes = Base32.FromBase32(unformattedKey);

            byte[] counter = BitConverter.GetBytes(window);

            if (BitConverter.IsLittleEndian) Array.Reverse(counter);

            HMACSHA1 hmac = new HMACSHA1(keyBytes);

            byte[] hash = hmac.ComputeHash(counter);

            int offset = hash[^1] & 0xf;

            // Convert the 4 bytes into an integer, ignoring the sign.
            var binary = ((hash[offset] & 0x7f) << 24) | (hash[offset + 1] << 16) | (hash[offset + 2] << 8) | (hash[offset + 3]);

            return binary % (int)Math.Pow(10, 6);
        }

        public static long GetCurrentCounter()
        {
            DateTime unixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

            return 30 - (long)(DateTime.UtcNow - unixEpoch).TotalSeconds % 30;
        }
    }

    [AllowAnonymous]
    public class TFAController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            string randomKey = TFAManager.GetAuthenticatorKey();

            TFAViewModel vm = new TFAViewModel();

            vm.User = User.Identity as System.Security.Claims.ClaimsIdentity;
            vm.RandomKey = randomKey;
            vm.RandomKeyFormatted = TFAManager.FormatKey(randomKey);
            vm.QRCodeData = TFAManager.QrCodeUri("AspNet2", "Emre", randomKey);

            return View(model: vm);
        }

        private JsonResult CreateCode(string authenticatorKey)
        {
            try
            {
                if (string.IsNullOrEmpty(authenticatorKey)) throw new ArgumentNullException(nameof(authenticatorKey));

                AuthCodeViewModel vm = new AuthCodeViewModel();

                // Code & Remaining Time From TFAManager
                // var code = TwoFactorAuth.GetAuthenticatorCode(authenticatorKey);
                // var remainingTime = TwoFactorAuth.GetCurrentCounter();

                // Code & Remaining Time From Otp.NET
                // https://github.com/kspearrin/Otp.NET
                // var totp = new Totp(Base32Encoding.ToBytes(authenticatorKey));
                var totp = new Totp(Base32Encoding.ToBytes(authenticatorKey), timeCorrection: new TimeCorrection(DateTime.UtcNow.AddSeconds(+1)));
                var code = totp.ComputeTotp();
                var remainingTime = totp.RemainingSeconds();

                vm.AuthCode = $"{code.PadLeft(6, '0')}";
                vm.RemainingTime = $"{remainingTime, 2:00}";

                return Json(vm);
            }
            catch (Exception ex)
            {
                AuthCodeViewModel vm = new AuthCodeViewModel() { AuthCode = "0", RemainingTime = "0", Message = ex.Message };
                return Json(vm);
            }
        }

        private string OtpVerify(string authenticatorKey, string totpCode)
        {
            var totp = new Totp(Base32Encoding.ToBytes(authenticatorKey));

            long timeWindowUsed;
            //var window = new VerificationWindow(previous: 1, future: 1);
            //bool result = totp.VerifyTotp(totpCode, out timeWindowUsed, window);
            bool result = totp.VerifyTotp(totpCode, out timeWindowUsed, VerificationWindow.RfcSpecifiedNetworkDelay);

            DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            DateTime timeWindowDate = epoch.AddSeconds(timeWindowUsed);

            return $"OTP: {result} {timeWindowUsed} {timeWindowDate.ToLongDateString()} {timeWindowDate.ToLongTimeString()}";
        }


        [HttpPost]
        public IActionResult Index(TFAViewModel model)
        {
            string authenticatorKey = model.RandomKey;

            return View(viewName: "Validate", model: authenticatorKey);
        }

        [HttpPost]
        public IActionResult ValidateResult(string authkey, string authcode)
        {
            string result = OtpVerify(authkey, authcode);

            return View(model: result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("get-auth-code")]
        public IActionResult GetAuthCode(string authenticatorKey)
        {
            return CreateCode(authenticatorKey);
        }
    }
}

AspNet2/Views/TFA/Index.cshtml
@model TFAViewModel

<div class="container-lg navbar-padding">

    <div class="row">

        <div class="col">

            <div class="jumbotron">

                <h1 class="display-4">İki Aşamalı Kimlik Doğrulama</h1>

                <hr />

                <form asp-controller="TFA" asp-action="Index" method="post">

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Kullanıcı ID</label>
                        <div class="col-sm-10">
                            <input asp-for="UserId" class="form-control" autocomplete="off" readonly />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Kullanıcı Adınız</label>
                        <div class="col-sm-10">
                            <input asp-for="UserName" class="form-control" autocomplete="off" readonly />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Yetki Kodu</label>
                        <div class="col-sm-10">
                            <input asp-for="RandomKeyFormatted" class="form-control" readonly />
                            <small class="form-text text-muted">Manuel girişlerde büyük/küçük harf ayrımı yoktur.</small>
                            <input asp-for="RandomKey" class="form-control" readonly type="hidden" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Yetki Kodu</label>
                        <div class="col-sm-10">
                            <div id="qrCode"></div>
                            <small class="form-text text-muted">Authenticator uygulaması ile okutabilirsiniz.</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-10">
                            <input type="submit" />
                        </div>
                    </div>



                </form>

            </div>

            <blockquote class="blockquote">
                <p class="mb-0">İki Faktörlü Kimlik Doğruluma</p>
                <footer class="blockquote-footer">Üretilen kodların uyumlu olması için sistemlerin satlerinin uyumlu olması gerekmektedir.</footer>
            </blockquote>

        </div>

    </div>

</div>

@section scriptSection {

    <script>
    new QRCode(document.getElementById("qrCode"),
        {
            text: "@Html.Raw(Model.QRCodeData)",
            width: 200,
            height: 200
        });
    </script>

}

AspNet2/Views/TFA/Validate.cshtml
@model string

<div class="container-lg navbar-padding">

    <div class="row">

        <div class="col">

            <div class="jumbotron">

                <h1 class="display-4">İki Aşamalı Kimlik Doğrulama</h1>

                <hr />

                <form name="validateForm" id="validateForm" asp-controller="TFA" asp-action="ValidateResult" method="post">

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Doğrulama Anahtarı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="authkey" id="authkey" readonly value="@Model" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Doğrulama Kodu</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="authcode" id="authcode" autocomplete="off" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-10">
                            <input type="submit" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-10">
                            <button type="button" class="btn btn-primary">
                                <b onclick="SetValue(this.id);" id="codeText">...</b> <span class="badge badge-light" id="code-remaining">.</span>
                            </button>
                        </div>
                    </div>

                </form>

            </div>

            <blockquote class="blockquote">
                <p class="mb-0">İki Faktörlü Kimlik Doğruluma</p>
                <footer class="blockquote-footer">Üretilen kodların uyumlu olması için sistemlerin satlerinin uyumlu olması gerekmektedir.</footer>
            </blockquote>

        </div>

    </div>

</div>

@section scriptSection {

<script>

    $(document).ready(function () {
        GetInfo();
        setInterval(GetInfo, 1000);
    });

    function GetVerificationToken() {
        var form = $('#validateForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();
        return token;
    }

    function GetInfo() {

        var jqxhr = $.ajax({
                method: "POST",
                url: "/get-auth-code",
                data: { __RequestVerificationToken: GetVerificationToken(), authenticatorKey: "@Model" }
            })
            .done(function (data, textStatus, jqXHR) {
                $("#codeText").html(data.authCode);
                $("#code-remaining").html(data.remainingTime);
            })
            .fail(function (jqXHR, textStatus, errorThrown) {     })
            .always(function (jqXHROrData, textStatus, jqXHROrErrorThrown) { })
        ;

    }

    function SetValue(id) {
        var code = $("#" + id).html();
        $("#authcode").val(code);
    }

</script>

}

AspNet2/Views/TFA/ValidateResult.cshtml
@model string

<div class="container-lg navbar-padding">

    <div class="row">

        <div class="col">

            <div class="jumbotron">

                <h1 class="display-4">İki Aşamalı Kimlik Doğrulama</h1>

                <hr />

                <form name="validateForm" id="validateForm" asp-controller="TFA" asp-action="Validate" method="post">

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Doğrulama Sonucu</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" autocomplete="off" value="@Model" />
                        </div>
                    </div>

                </form>

            </div>

            <blockquote class="blockquote">
                <p class="mb-0">İki Faktörlü Kimlik Doğruluma</p>
                <footer class="blockquote-footer">Üretilen kodların uyumlu olması için sistemlerin satlerinin uyumlu olması gerekmektedir.</footer>
            </blockquote>

        </div>

    </div>

</div>